# Color scheme
import = ["~/.config/alacritty/dracula.toml"]

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
size = 14.0

[window]
opacity = 0.95
dimensions = { columns = 100, lines = 30 }
padding = { x = 15, y = 10 }
